#!/bin/sh

playerctl -F -p Lollypop status |
    while read -r STATUS; do
        if [ "$STATUS" = "Playing" ]; then
            STATUS=""
        else
            STATUS=""
        fi
        echo "$STATUS"
    done
