#!/bin/sh

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(paru -Qua 2> /dev/null | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$updates" -gt 0 ]; then
    seq "$updates"
    #echo "<span foreground='#3b4252'> | </span><span font_desc='Font Awesome 5 Free Solid' foreground='#bf616a'></span> $updates"
    #echo "%{F#bf616a}%{F-} $updates"
fi

