#!/bin/sh

userresources=$HOME/.config/x11/Xresources
usermodmap=$HOME/.config/x11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

#Source env vars
source ~/.config/x11/xprofile

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

## X specific settings
xset s 0 0
xset dpms 0 0 0
xset r rate 440 50
numlockx &

lockscreen.sh &
sleep 1
exec qtile start -b x11
