#!/bin/sh

#cmd="$(termite --name "findFiles" -e "zsh -ic \"fd --hidden | fzf --reverse --border=horizontal --no-info --prompt ' │ ' --pointer '― ' --header=' ' | grep '\S' | tee .fzf-dir\"")"
#dir=$(cat .fzf-dir)
#if [[ -d $dir ]]; then
#	termite -e "zsh -ic \"ranger $dir\""
#elif [[ -f $dir ]]; then
#	rifle $dir
#else
#	exit
#fi

urxvt -g 75x50 -name "findFiles" -e zsh -ic "fd --hidden --type file | fzf --reverse --border=horizontal --no-info --header=' ' --prompt ' │ ' --pointer '― ' -e | xargs rifle"
