#!/bin/bash

# colorscheme for fzf
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'  --color fg:7,bg:-1,hl:6,fg+:6,bg+:-1,hl+:6 --color info:2,prompt:1,spinner:5,pointer:5,marker:3,header:8'

set -u
set -e

readonly NOTES_FILE=~/.fzf_notes

if [[ ! -a "${NOTES_FILE}" ]]; then
    echo "empty" >> "${NOTES_FILE}"
fi

function get_notes()
{
    cat ${NOTES_FILE}
}

function main()
{
    local all_notes="$(get_notes)"

    local note=$( (echo "${all_notes}")  | fzf --print-query --reverse --border=horizontal --no-info --header=" " --prompt ' │ ' --pointer '― ' | awk '!seen[$0]++' | grep "\S")
    local matching=$( (echo "${all_notes}") | grep "^${note}$")

    if [[ -n "${matching}" ]]; then
        local new_notes=$( (echo "${all_notes}")  | grep -v "^${note}$" )
    else
        local new_notes=$( (echo -e "${all_notes}\n${note}") | grep -v "^$")
    fi

    echo "${new_notes}" > "${NOTES_FILE}"
}

main
