#!/bin/sh

# colorscheme for fzf
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'  --color fg:7,bg:-1,hl:6,fg+:6,bg+:-1,hl+:6 --color info:2,prompt:1,spinner:5,pointer:5,marker:3,header:8'

if [ $(bspc query -N -n .hidden | wc -l) = "0" ]; then
	notify-send -u normal -t 3000 "No windows hiddened"	
	#dunstify -u normal -t 3000 -r 7729 "No windows hiddened"
else
	list=$(bspc query -N -n .hidden | xargs -n1 xdotool getwindowname)
	notify-send -u normal -t 3000 "Windows hiddened:" "$list"
	#dunstify -u normal -t 3000 -r 7729 "Windows hiddened:" "$list"
fi

