#!/bin/sh

# colorscheme for fzf
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'  --color fg:7,bg:-1,hl:6,fg+:6,bg+:-1,hl+:6 --color info:2,prompt:1,spinner:5,pointer:5,marker:3,header:8'

selector=$(bspc query -N -n)
windows=($(bspc query -N -n .window | grep -v "$selector"))
index="$(for i in "${!windows[@]}"; do printf "%s %s\n" $i "$(xdotool getwindowname ${windows[i]})"; done | fzf --reverse --border=horizontal --no-info --header=" " --prompt '□ │ ' --pointer '― ')" &&
	if [ "$index" = "" ];
	then
		exit 0
	else

		bspc node -f "${windows[${index%% *}]}"
	fi

