#! /bin/sh
# _
#| |__  ___ _ ____      ___ __ ___  _ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | (__
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#          |_|
##############################################

#Pretty fade-in from blurred login screen
#if [ ! -f /tmp/bspwm-startup.lock ]; then
#    feh --no-fehbg --bg-fill "/home/barbarossa/.cache/feh-blur/blur-1.ppm"
#    sleep 0.005
#    feh --no-fehbg --bg-fill "/home/barbarossa/.cache/feh-blur/blur-0.ppm"
#    sleep 0.005
#    feh --no-fehbg --bg-fill "/home/barbarossa/.cache/feh-blur/original.ppm"
#fi

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &
#pgrep -x sxhkd > /dev/null || sxhkd &

###Config

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor DP-4 -d          

bspc config border_width        3
bspc config top_padding         68
bspc config right_padding       9
bspc config left_padding        9
bspc config bottom_padding      9
bspc config window_gap          18
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

. "${HOME}/Public/neat-things/colorschemes/nord-xresources/src/nord.sh"
bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
#bspc config pointer_follows_focus true

###Rules
# Cleanup
bspc rule -r '*'

# State rules
bspc rule -a "Emacs" state=tiled
bspc rule -a "GNvim" state=tiled
bspc rule -a Alacritty:cmatrixterm state=fullscreen
bspc rule -a Alacritty:dropdown state=floating
bspc rule -a "Org.gnome.Nautilus" state=floating
bspc rule -a "Eog" state=floating
bspc rule -a "feh" state=floating
bspc rule -a "Gnome-calculator" state=floating
bspc rule -a "Blueberry.py" state=floating
bspc rule -a "Yad" state=floating
bspc rule -a "scrcpy" state=floating
bspc rule -a "Gfeeds" state=tiled
#bspc rule -a "pomotroid" state=floating
#bspc rule -a "Farge" state=floating
#bspc rule -a "mpv" state=floating
#bspc rule -a "Gifview" state=floating
#bspc rule -a "Zathura" state=tiled

# Assignment rules
bspc rule -a "Chromium" desktop=^1 follow=on
bspc rule -a "Geary" desktop=^2 follow=on
bspc rule -a "Ptask" desktop=^2 follow=on
bspc rule -a "Io.elementary.calendar" desktop=^2 follow=on
bspc rule -a "Joplin" desktop=^3 follow=on
bspc rule -a "libreoffice-*" desktop=^3 follow=on #Fix me
bspc rule -a "Evince" desktop=^3 follow=on
bspc rule -a "code-oss" desktop=^4 follow=on
bspc rule -a "Slack" desktop=^6 follow=on
bspc rule -a "discord" desktop=^6 follow=on
bspc rule -a "Polari" desktop=^6 follow=on
#bspc rule -a "spotify" desktop=^7 follow=on
bspc rule -a "Gimp-2.99" desktop=^8 follow=on
bspc rule -a "Lxappearance" desktop=^10 follow=on
bspc rule -a "Pavucontrol" desktop=^10 follow=on
bspc rule -a "Connman-gtk" desktop=^10 follow=on

### Non-bspwm specific settings
xset s 0 0
xset dpms 0 0 0
(sleep 10; xset r rate 440 50) & #Doesnt work imediately at startup for some odd reason. The other xset commands seem fine
xsetroot -cursor_name left_ptr &
numlockx &
#xset +fp ~/.fonts/misc/
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'

###Application startup
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    touch /tmp/bspwm-startup.lock
    picom --experimental-backends &
    ~/.fehbg &
    ~/.config/polybar/launch.sh &
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
    dunst &
    pidswallow -l &
    unclutter &
    greenclip daemon &
    an2linuxserver.py &
    flashfocus &
    autoadb scrcpy -s '{}' &
    xidlehook --not-when-fullscreen --not-when-audio --timer 420 'screensaver' '' --timer 180 'xset dpms force off; if pgrep lockscreen.sh 2>/dev/null; then true; else lockscreen.sh; fi' '' &
    syncthing -no-browser &
    synergys &
    mkfifo /tmp/vol && echo "$(pulsemixer --get-volume | awk '{print $1}')" > /tmp/vol &
    mkfifo /tmp/vol-icon && ~/.config/qtile/eww_vol_icon.sh mute &
    redshift -l 39.2904:-76.6122 &
    lead &
    ~/.config/eww/scripts/getweather &
    gitwatch -r pi@192.168.0.18:/mnt/fd1/repos/tower-dotfiles /home/barbarossa/Public/tower-dotfiles &
    feh-blur --darken 0 -b 6 &
    eww daemon &
    emacs --daemon &
    emacs --daemon=term &

    lockscreen.sh

    ## Default layout
    bspdefaultlayout.sh
fi

