#!/bin/sh

case $1 in
prev)
	if pidof mpd
		then
		mpc prev
		
		else
		playerctl previous
	fi
	;;
next)
	if pidof mpd
		then
		mpc next

		else
		playerctl next
	fi
	;;
play-pause)
	if pidof mpd
		then
		mpc toggle

		else
		playerctl play-pause
	fi
	;;
stop)
	if pidof mpd
		then
		mpc stop

		else
		playerctl stop
	fi
	;;
esac
